# importing csv module
import csv
import glob
import os

# csv file name
filename = "Pablo3.csv"

# initializing the titles and rows list
fields = []
rows = []

# reading csv file
with open(filename, 'r') as csvfile:
	# creating a csv reader object
	csvreader = csv.reader(csvfile)
	
	# extracting field names through first row
	fields = next(csvreader)

	# extracting each data row one by one
	for row in csvreader:
		rows.append(row)

	# get total number of rows
	print("Total no. of rows: %d"%(csvreader.line_num))

# printing the field names
print('Field names are:' + ', '.join(field for field in fields))

# printing data in JSON files in metadata folder
os.chdir("./metadata")
print('\nNow writing JSON files...\n')
f_total = open("_metadata.json", "w+")
f_total.write('[\n')
for row in rows[:200]:
    f = open((row[0]) + ".json", "w+")
    #write to the individual json file
    #Background,Body,Ear,Head,Mouth,Right Eye,Left Eye,Right Eyebrow,Left Eyebrow,Clothing,Jewelry,Headwear,Name
    f.write('{\n')
    f.write('    "name": "'+row[0]+'",\n')
    f.write('    "description": "'+row[1]+'",\n')
    f.write('    "image": "'+row[2]+'",\n')
    f.write('    "attributes": [\n')
    f.write('      {\n')
    f.write('        "trait_type": "Background",\n')
    f.write('        "value": "'+row[3]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Body",\n')
    f.write('        "value": "'+row[4]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Ear",\n')
    f.write('        "value": "'+row[5]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Head",\n')
    f.write('        "value": "'+row[6]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Mouth",\n')
    f.write('        "value": "'+row[7]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Right Eye",\n')
    f.write('        "value": "'+row[8]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Left Eye",\n')
    f.write('        "value": "'+row[9]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Right Eyebrow",\n')
    f.write('        "value": "'+row[10]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Left Eyebrow",\n')
    f.write('        "value": "'+row[11]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Clothing",\n')
    f.write('        "value": "'+row[12]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Jewelry",\n')
    f.write('        "value": "'+row[13]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Headwear",\n')
    f.write('        "value": "'+row[14]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Name",\n')
    f.write('        "value": "'+row[15]+'"\n')
    f.write('      },\n')
    f.write('      {\n')
    f.write('        "trait_type": "Generation",\n')
    f.write('        "value": "'+row[16]+'"\n')
    f.write('      }\n')
    f.write('    ]\n')
    f.write('  }\n')
    f.close()
    #write to the total json file
    f_total.write('  {\n')
    f_total.write('    "name": "'+row[0]+'",\n')
    f_total.write('    "description": "'+row[1]+'",\n')
    f_total.write('    "image": "'+row[2]+'",\n')
    f_total.write('    "attributes": [\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Background",\n')
    f_total.write('        "value": "'+row[3]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Body",\n')
    f_total.write('        "value": "'+row[4]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Ear",\n')
    f_total.write('        "value": "'+row[5]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Head",\n')
    f_total.write('        "value": "'+row[6]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Mouth",\n')
    f_total.write('        "value": "'+row[7]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Right Eye",\n')
    f_total.write('        "value": "'+row[8]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Left Eye",\n')
    f_total.write('        "value": "'+row[9]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Right Eyebrow",\n')
    f_total.write('        "value": "'+row[10]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Left Eyebrow",\n')
    f_total.write('        "value": "'+row[11]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Clothing",\n')
    f_total.write('        "value": "'+row[12]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Jewelry",\n')
    f_total.write('        "value": "'+row[13]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Headwear",\n')
    f_total.write('        "value": "'+row[14]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Name",\n')
    f_total.write('        "value": "'+row[15]+'"\n')
    f_total.write('      },\n')
    f_total.write('      {\n')
    f_total.write('        "trait_type": "Generation",\n')
    f_total.write('        "value": "'+row[16]+'"\n')
    f_total.write('      }\n')
    f_total.write('    ]\n')
    f_total.write('  },\n')
f_total.write(']\n')
f_total.close()